title: Moe Dewedar
description: "OMSCS @ Georgia Tech · Interests: AI, ML, Data Science, Software Engineering"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
url: https://mohaned-dewedar.github.io
